# Generated by Django 5.2.4 on 2026-05-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_about_alter_user_github_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Эксплуатант', 'verbose_name_plural': 'Эксплуатанты'},
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=124, verbose_name='Навык'),
        ),
    ]
