STATUS_OPENED = 'open'
STATUS_CLOSED = 'closed'
MAX_LENGTH_PROJECT = 200
MAX_LENGTH_STATUS = 6
PAGINATION = 12

MAX_LENGTH_SKILL = 124
MAX_LENGTH_NAME = 124
MAX_LENGTH_PHONE = 12
MAX_LENGTH_ABOUT = 256
COUNT_OF_DISPLAYED = 10
# так все же лучше в каждом приложении свой файлик или общий на весь проект?
